add option to only play sound when window is focussed
amq-script-project/AMQ-Scripts pull request #21
Opened 2023-08-08 17:53 UTC by kempanator

2023-08-08 21:44 UTC, Zolhungaj commented
It's not technically wrong. But could you change the spelling from "focussed" to "focused"?

2023-08-08 21:45 UTC, Zolhungaj requested changes
Focussed -> focused

2023-08-08 22:01 UTC, kempanator commented
fixed

2023-08-11 21:38 UTC, Zolhungaj approved these changes
LGTM

2023-08-11 21:38 UTC, Zolhungaj commented on gameplay/amqShowPingPong.user.js
> +// @version      1.0.1
Pretty sure this script stopped working when the game switched to socket-io 4

2023-08-11 21:38 UTC, merged